services:
  app:
    build: .
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=production
      - PORT=8001
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped