name: Deploy to Production

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest

        steps:
            - name: Deploy to VPS
              uses: appleboy/ssh-action@v0.1.10
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USER }}
                key: ${{ secrets.KEY }}
                script: |
                    echo "File management"
                    cd /home/boss/server-deploy
                    echo "Pulling latest changes"
                    git pull origin main
                    echo "Installing dependencies"
                    pnpm install --frozen-lockfile
                    echo "Building the project"
                    pnpm build
                    echo "Restarting the project"
                    pm2 restart all