name: Deploy to Production

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Deploy to VPS
              uses: appleboy/ssh-action@v0.1.10
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USER }}
                key: ${{ secrets.KEY }}
                script: |
                    cd /var/www/express-app
                    git pull origin main
                    pnpm install --frozen-lockfile
                    pnpm build
                    pm2 restart all